import os

WIN_WIDTH = 800
WIN_HEIGHT = 800
ENTITY_SIZE = 80
TILE_SIZE = 100
FPS = 60
MOVEMENT_SUBSTEP_COUNT = 5

UI_LAYER = 6
WEAPON_LAYER = 5
PLAYER_LAYER = 4
DARKNESS_LAYER = 3
ENEMY_LAYER = 2
BLOCK_LAYER = 1
START_PLAYER_HEALTH = 1000
CURRENT_PLAYER_HEALTH = 1000
START_PLAYER_SPEED = 5
START_PLAYER_LIGHT_RANGE = 5
LIGHT_INTENSITIES_COUNT = 5

ENEMY_SPEED = 5

HEALTH_BAR_WIDTH = 25
HEALTH_BAR_HEIGHT = 20

LIGHT_ADAPTION_TIME = 0.5

SOUND_FOLDER = "sounds"
MUSIC_FOLDER = os.path.join(SOUND_FOLDER, "music")
LEVEL_SOUNDTRACK = os.path.join(MUSIC_FOLDER, "Pharaoh's Tomb Soundtrack final.mp3")

IMAGE_FOLDER = "img"
PORTAL_SPRITE_PATH = os.path.join(IMAGE_FOLDER, "portal.png")
FLOOR_SPRITE_PATH = os.path.join(IMAGE_FOLDER, "floorbig.png")

MUSIC_VOLUME = 1


def NEW_HEALTH():
    global CURRENT_PLAYER_HEALTH
    CURRENT_PLAYER_HEALTH -= 1
    print(CURRENT_PLAYER_HEALTH)
    return CURRENT_PLAYER_HEALTH


def CURRENT_HEALTH():
    return CURRENT_HEALTH()


def CURRENT_SPEED():
    return START_PLAYER_SPEED


def NEW_SPEED():
    global START_PLAYER_SPEED
    START_PLAYER_SPEED += 2/5 * ( 10 - START_PLAYER_SPEED)

    return START_PLAYER_SPEED


RED = (255, 0, 0)
BLACK = (0, 0, 0)
ENEMY_COLOR = (88, 55, 111)
SAND_COLOR = (194, 178, 128)
BOOST_COLOR = (222, 111, 112)


